### PR TITLE
update to 20200226

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
note that these recent releases of git-annex would break datalad prior yet to be released 0.12.3, due to breakage of API (removal of `--include-dotfiles` in  [7.20191218-128-g3cd375723 AKA 8.20200226~73](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7.20191218-128-g3cd375723)

**Comment by notestaff** [comment]
Maybe add constraints on git-annex version to  datalad-feedstock?

I wonder why —include-dotfiles could not be made a no-op for backwards compatibility...

**Comment by yarikoptic** [comment]
> Maybe add constraints on git-annex version to datalad-feedstock?

we might, e.g. could have been `<=8` (or whatever syntax is), and in the next update I will do `<=9`.
I wish there was "Breaks" relationship in conda to be declared in git-annex pkg like we do in debian

**Comment by yarikoptic** [comment]
> I wonder why —include-dotfiles could not be made a no-op for backwards compatibility...

well, I wondered too, and even whined a (just a tiny) bit to joey ;)  moreover, there might be side-effects in adjusted branches (ref: https://github.com/datalad/datalad/pull/4214#issuecomment-592536329)

**Pull request merged**
