### PR TITLE
added testing of downstream packages annexremote and datalad

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
(continued from #98)
@yarikoptic when you have time, can you look at the causes of datalad test failures here?  there seem to be different failures with the standard and the standalone git-annex builds.

**Comment by yarikoptic** [comment]
woohoo -- fetched 167MB [log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/209014/logs/13).  Largely due to the run of 
```
python -c 'from annexremote import Master, SpecialRemote, RemoteError'
```
better be probably `2>&1 | tee -n 1000` or smth like that for that one.  I guess to be addressed at the annexremote feedstock level?

datalad failed only 1 test and very interestingly and I filed https://github.com/datalad/datalad/issues/4921  with more details:

```
2020-09-14T06:57:15.2915093Z ======================================================================
2020-09-14T06:57:15.2915566Z FAIL: datalad.tests.test_witless_runner.test_runner_parametrized_protocol
2020-09-14T06:57:15.2916282Z ----------------------------------------------------------------------
2020-09-14T06:57:15.2916765Z Traceback (most recent call last):
2020-09-14T06:57:15.2918077Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600056447586/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
2020-09-14T06:57:15.2919171Z     self.test(*self.arg)
2020-09-14T06:57:15.2920772Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600056447586/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/test_witless_runner.py", line 149, in test_runner_parametrized_protocol
2020-09-14T06:57:15.2922014Z     eq_(res['stdout'], '5')
2020-09-14T06:57:15.2922684Z AssertionError: '55' != '5'
```

there is no easy way to provision skipping of a single test here, right?

PS I checked only a single build/run

**Comment by notestaff** [comment]
"there is no easy way to provision skipping of a single test here, right?" -- to skip it here but still have it in datalad-feedstock, no; but if this failure is not important, maybe silence it in datalad-feedstock?

**Comment by notestaff** [comment]
@yarikoptic the standard build got fixed.  the standalone one still has some (different?) errors.

**Comment by yarikoptic** [comment]
I think all three failing tests are something we haven't seen before failing, filed https://github.com/datalad/datalad/issues/4933 and https://github.com/datalad/datalad/issues/4932 , we will try to look into them soonish than laterish

**Comment by notestaff** [comment]
@yarikoptic I'm going to enable downstream testing of datalad just for the standard git-annex build for now.  Let me know when these other failures get fixed.   If you think these failures might reflect real issues, maybe for now change the [git-annex dependency in datalad-feedstock](https://github.com/conda-forge/datalad-feedstock/blob/master/recipe/meta.yaml#L42) to `=*=alldep*` to force installation of the standard version?  (Also, that dependency doesn't specify a minimal git-annex version -- maybe it should?)

**Comment by yarikoptic** [comment]
I have not looked into the nature of those failures -- will try in a few days to make a decision either version restriction is indeed due or a quick bug fix is possible.  Limiting downstream testing for now sounds like a good plan, thank you @notestaff !

**Pull request closed without merging**
