### PR TITLE
build ghc then git annex 01

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
@notestaff I would like to introduce you to Florian (@eggzilla) he tries hard to get a Haskell stack into conda-forge. Maybe you both can exchange some experience.

**Comment by notestaff** [comment]
Thanks @bgruening !  Some others with interest in making Haskell work on conda: @luispedro @joeyh .

This PR might be a start for making ghc work on conda, but it has issues.  Most concerning is that the built ghc fails some tests in the ghc test suite.  It also uses two ugly hacks: (1) installs shim scripts to ensure that gcc is always called with certain flags, and (2) replaces libpthread in the sysroot of gcc_linux-64 with a symlink to /lib64/pthread .  
So while this PR works for building git-annex -- the git-annex test suite passes -- I'd be wary of putting it on ghc-feedstock until the ghc test suite issue is fixed.
Also, maybe the right way to build ghc is as a pseudo-cross-compiler, like gcc_linux-64 is, with $HOST as the target.  But I don't have enough understanding of cross-compiling toolchains.
The homebrew forumula for ghc might be a guide: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghc.rb

**Comment by luispedro** [comment]
This is such an amazing tour de force.

**Comment by yarikoptic** [comment]
Looking at https://anaconda.org/conda-forge/ghc and https://anaconda.org/conda-forge/ghc/files suggesting that we had `ghc` package in conda-forge for 4 years (so likely before this PR) I am confused why that `ghc` was not used ...

**Comment by luispedro** [comment]
The `conda-forge` GHC package is both old (`v8.10`), not 100% complete. Maybe that's enough for git-annex, but it's not a complete GHC solution

**Comment by yarikoptic** [comment]
git-annex needs 8.10.7 but may be that it was outdated back then or incomplete indeed was the reason. @notestaff would be the only one to know I guess ;)

**Pull request closed without merging**
