### PR TITLE
MNT: Re-rendered with conda-build 3.17.8, conda-smithy 3.2.14, and co…

### PR DESCRIPTION
**Pull request by notestaff**
…nda-forge-pinning 2019.03.12; now building from source again, using some ugly hacks

Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
todo: add to LDFLAGS etc, not replace

**Comment by notestaff** [comment]
@conda-forge/core Can you please check if a hack I used to get this recipe to build is safe/valid?  In build.sh I did

rm ${BUILD_PREFIX}/${HOST}/sysroot/usr/lib/libpthread.so
 ln -s /lib64/libpthread.so.0 ${BUILD_PREFIX}/${HOST}/sysroot/usr/lib/libpthread.so

Is there a less hacky / proper way to fix the linking error that happens without these lines?

**Comment by notestaff** [comment]
@yarikoptic @joeyh i’ve found a pair of ugly hacks that seems to work for building the git-annex recipe with the current conda-forge.  maybe, try it to see if it installs and works ok on your systems?

**Comment by yarikoptic** [comment]
Only for Linux, right?

**Comment by notestaff** [comment]
yes

**Comment by yarikoptic** [comment]
installed, ran annex test -- all clear.  Installed datalad and ran its tests - discovered only datalad related issues (https://github.com/datalad/datalad/issues/3224) so afaik all good

**Pull request merged**
