### PR TITLE
update to 7.20181105

### PR DESCRIPTION
**Pull request by notestaff**
update to 7.20181105

### CODE REVIEW

**Comment by yarikoptic** [comment]
Is there a way to declare that this would break `datalad <= 0.11.1` (yet to be released ;))?

**Comment by notestaff** [comment]
@yarikoptic You can specify that in the datalad recipe:
https://github.com/conda-forge/datalad-feedstock/blob/master/recipe/meta.yaml#L40
using the syntax from here:
https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html#package-match-specifications

**Comment by notestaff** [comment]
p.s. did you mean datalad >= 0.11.1 ?

**Comment by yarikoptic** [comment]
nope... I did mean "Breaks: datalad <= 0.11.1" to be declared within `git-annex` package ;)  
It is a way we use in Debian to declare that some "root" package breaks some 3rd party packages relying on it. That prevents upgrade of the root package until 3rd party packages can be updated to that version which is known to tolerate such new root package.  `pip` doesn't have a way to do such specifications and I wouldn't be surprised if conda neither.  In that page I found nothing to declare it.
It comes quite handy, and could be used in conda e.g. for recent keyring/keyrings.alt ... at least it is easy to quickly push new release (of keyrings.alt in that case) but some user systems might remain broken until they are upgraded in full

**Comment by notestaff** [comment]
@yarikoptic I don't think conda supports this.  If git-annex versions followed https://semver.org/ you could declare datalad dependence on the current major version and know it won't break the spec; but git-annex doesn't.  The solution is to update recipes for past datalad versions with new build numbers, adding a constraint on git-annex version.

**Comment by notestaff** [comment]
@yarikoptic Do you want to hold off on merging this git-annex update until you do that?

**Comment by yarikoptic** [comment]
Since we have them only got Linux, probably don't bother - majority if not all tests should be passing and we will issue a bug fix soon for datalad

**Pull request merged**
