### PR TITLE
update to 7.20190615

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Note that current release has a quite notable usability issue which also triggers many tests failures for datalad: https://git-annex.branchable.com/bugs/annex_init_no_longer_generates_default_description/#comment-474645608272bbb5fd611661e82fb7d5

**Comment by notestaff** [comment]
@conda-forge/core @conda-forge/conda-build @conda-forge/conda-build-all  Could someone help me understand the conda-build errors/warnings printed when building this release?   The package itself seems to work fine (apart from the errors in a supplementary test suite, which are a separate issue); but can the warnings like below be ignored?

ERROR :: get_rpaths_raw()=['/home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/lib:/home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib'] and patchelf=/home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/lib:/home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib disagree for /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/git-annex :: 
Warning: rpath /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/lib is outside prefix /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p (removing it)
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/nl_NL@euro did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/nl_NL@euro did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/ib/libdl-2.12.2.so did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/ib/libdl-2.12.2.so did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/igmp.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/igmp.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/bits/stropts.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/bits/stropts.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/fo_FO did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/fo_FO did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/lib/gconv/KOI8-RU.so did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/lib/gconv/KOI8-RU.so did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/can/netlink.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/can/netlink.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/netfilter/xt_owner.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/netfilter/xt_owner.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/mai_IN did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/mai_IN did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/ib/libcrypt.so.1 did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/ib/libcrypt.so.1 did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/netax25/ax25.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/netax25/ax25.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/if_pppox.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/include/linux/if_pppox.h did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/zh_CN did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/
ERROR:conda_build.utils:Glob /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/sr/share/i18n/locales/zh_CN did not match in root_dir /home/conda/feedstock_root/build_artifacts/git-annex_1560821549741/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/

Thanks!

**Comment by notestaff** [comment]
@yarikoptic have you heard from @joeyh whether a bug-fix release is planned soon?

**Comment by scopatz** [comment]
I think those errors are safe to ignore

**Comment by yarikoptic** [comment]
Not yet, but I also didn't inquire in person yet

**Pull request closed without merging**
