### PR TITLE
ENH: ppc64 

### LINKED ISSUE #108: enable linux-ppc64 build
may be after #107 to minimize possible conflicts

@satra has a use-case/demand

### PR DESCRIPTION
**Pull request by yarikoptic**
and aarch64 

Closes #108

### CODE REVIEW

**Comment by yarikoptic** [comment]
@conda-forge-admin please rerender

**Comment by yarikoptic** [comment]
for aarc64: https://cloud.drone.io/conda-forge/git-annex-feedstock/1/1/2
```

File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 288, in verify_specs
--
381 | raise ResolvePackageNotFound(bad_deps)
382 | conda.exceptions.ResolvePackageNotFound:
383 | - stack
384 | - findutils

```
and similarly for ppc64
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-ppc64le: {'findutils', 'stack'}
```
so first would need to be looked at those feedstocks

**Comment by notestaff** [comment]
@conda-forge-admin, please rerender

**Comment by notestaff** [comment]
@yarikoptic is this PR still relevant?  should it be tried with the current master version?

**Comment by yarikoptic** [comment]
let's forget about it for now

**Pull request closed without merging**
