### PR TITLE
re-enable standalone package build (possibly with different git-annex version); rerender with conda smithy 200804

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
why "standalone"?  it is slower due to all the shimming.  We switched to use conda build of git-annex since it lets our datalad tests run faster.  Is such switch needed?

**Comment by notestaff** [comment]
@yarikoptic standalone is a fallback variant, for when the standard build cannot be installed into a conda environment at all, due to package conflicts between git-annex dependencies and other packages being installed into that environment.   meta.yaml gives the standard version a higher build number, to tell conda to prefer it over the standalone version.

the better solution is of course to fix whatever package conflicts exist, but if you've tried that in practice you know it's a waste of life...

**Comment by yarikoptic** [comment]
oh, it just enables BOTH builds!  Will `nodep` build have annotation in the version like I see a single one with nodep in https://anaconda.org/conda-forge/git-annex/files .  I also hope that typically the most recent version would be "native" build.  Is that what you are aiming for as well?

**Comment by notestaff** [comment]
@yarikoptic "Will nodep build have annotation in the version" -- you mean in the build string?  The build string includes 'nodep'.  Maybe should make the standard build string include 'std' so people can exclude 'nodep' when specifying dependencies on git-annex, if they want to?

"hope that typically the most recent version would be "native" build" -- yes.  If there is a nodep build for the same git-annex version it will have a lower build number.

**Comment by yarikoptic** [comment]
> the better solution is of course to fix whatever package conflicts exist, but if you've tried that in practice you know it's a waste of life...

ha ha ;) indeed, somewhat ... "of maintainer life" but total loss (amortized through users) is likely larger. But indeed "maintainer sacrifice" is needed and not really desired ;)

What conflicts ATM are?

**Comment by notestaff** [comment]
"What conflicts ATM are?" -- that would depend on the conda env into which you're trying to install git-annex.

**Pull request merged**
