### PR TITLE
added testing of downstream packages

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- testing against datalad again would be awesome.  I guess some `PATH` tune up is needed (or built conda package installed?) to test though: datalad tests fail with `git-annex of version >= 7.20190503 is missing`

**Comment by notestaff** [comment]
@yarikoptic The version that failed installs the standalone distribution.  But why does datalad think git-annex is not available?  How does it check for that?

**Comment by notestaff** [comment]
@yarikoptic  The standalone package installs into $PREFIX/bin/git-annex a symlink to ../share/PKG_STRING/git-annex -- maybe that somehow confuses datalad's version determination, or its way of running git-annex?

**Comment by notestaff** [comment]
@yarikoptic Test with the standard package succeeded, so the issue is something specific to the nodep (standalone) package.  How does datalad determine the git-annex version?  (Not by running `git-annex version`?)

**Comment by yarikoptic** [comment]
AFAIK datalad does nothing special: it  uses`git annex`  as available within PATH to call `git annex version --raw` and if that fails `git annex version`.  Code is https://github.com/datalad/datalad/blob/master/datalad/support/external_versions.py#L55

**Comment by yarikoptic** [comment]
In the [log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/196072/logs/10) I see even `FileNotFoundError: [Errno 2] No such file or directory: 'git'` - so it doesn't find `git` either...

**Comment by notestaff** [comment]
Does it expect to find git next to the git-annex binary?  In the standalone package , git is not installed there.   But 'git-annex version' should still work.

**Comment by notestaff** [comment]
Maybe, add git as a runtime dependency of datalad?

**Comment by yarikoptic** [comment]
> Maybe, add git as a runtime dependency of datalad?

ah, I guess nodep build of git-annex doesn't have `git` as a dependency and thus hell breaks loose.  Ok, I will add now. https://github.com/conda-forge/datalad-feedstock/pull/37/files

**Comment by yarikoptic** [comment]
new datalad build with `git` dependency was merged in, I have restarted this failing `nodepTrue` run here (at the level of github workflow)

**Pull request closed without merging**
