### PR TITLE
update to git annex 8.20211231

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
@conda-forge/core After latest re-render, getting strange build errors early in the build complaining about issues with the python package being outdated -- but python isn't a dependency of this recipe, so not sure why it needs python at all (let alone the python 2.0 it seems to be trying to install).   Any suggestions on how to debug this?  Thanks a lot!

**Comment by beckermr** [comment]
Try turning off mambabuild by setting the key in the conda-forge.yaml to false. 

@wolfv when you are back online can you look at this solve?

**Comment by wolfv** [comment]
the problem seems to come from `dbus` requiring an unconstrained `glib`. That glib in turn requires an unconstrained `python`.
It ends up there because `openssh` hasn't been built with `openssl 3.*` and the older python versions don't require openssh at all.

It resolves fine with `libffi=3.4` (not 3.3) so maybe that would be the best way to fix this (migration seems to be open).

**Comment by izahn** [comment]
The `libffi 3.4` migration PR had conflicts, I asked the bot to open https://github.com/conda-forge/git-annex-feedstock/pull/135 for you. Basically that one should be merged first and then this one.

**Pull request closed without merging**
