### PR TITLE
fixing version specs for downstream dependencies

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
so it is all good !? I guess I will need to check nodepTrue one some time later on WTF is so special about it ;)

**Comment by notestaff** [comment]
@yarikoptic actually, for some reason, latest datalad could not be installed with latest git-annex for testing, so the downstream testing got skipped:  https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/225307/logs/15
If you have any ideas as to the cause, that'd be great (but I'm not crazy to think the current conda error messages on this are unusable right :) )

**Comment by notestaff** [comment]
@yarikoptic tried re-rendering datalad with current conda-smithy, if doesn''t help will ping conda-forge admins.

re: nodepTrue, if want to use it, maybe check with @joeyh if he can [automate the build](https://git-annex.branchable.com/forum/standalone_tarballs_for_specific_versions/#comment-a3155f2e1ee583ea1cf20319be1ee865) or [adapt it to CentOS](https://git-annex.branchable.com/install/Linux_standalone/) so conda-forge can build it.
Could also try to reduce the chance of package conflicts by prodding git-annex/datalad dependencies to rerender their feedstocks.

One other recent change is [turning on compiler optimizations for gcc/ghc](https://github.com/conda-forge/git-annex-feedstock/commit/903b2f1004403520696c823466d4aa0197313952), should not break anything but just in case, watch for any odd changes.

**Comment by yarikoptic** [comment]
<details>
<summary>didn't check what is the latest annex but overall install seems to be ok</summary> 

```shell
$> conda create -c conda-forge -n datalad-test-install datalad=0.13.4 
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/yoh/anaconda-5.2.0-2.7/envs/datalad-test-install

  added / updated specs:
    - datalad=0.13.4


The following NEW packages will be INSTALLED:

...
  git                conda-forge/linux-64::git-2.28.0-pl526h5e3e691_1
  git-annex          conda-forge/linux-64::git-annex-8.20201007-alldep_h75db294_101
...
```
</details>
not sure if anything to fix on datalad end

**Comment by notestaff** [comment]
for a test install you also need to install the test dependencies of datalad

**Comment by notestaff** [comment]
"not sure if anything to fix on datalad end" -- the only thing I can think of is re-rendering with the latest conda-smithy; if that doesn't help, next stop is to ask conda-forge/core .

**Pull request closed without merging**
