### PR TITLE
add standalone build

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
What problem did this solve?
 If we go this way, I would love to see osx and windows builds in ;-)

**Comment by notestaff** [comment]
The problem of package conflicts: https://github.com/conda/conda/issues/9707#issuecomment-591620182
Do you know a systematic way to debug them?

This way, the standard git-annex package is still preferred, but if it has conflicts, conda can fall back on the dependency-less one.

The standalone build is only for Linux, no?

**Comment by yarikoptic** [comment]
> Do you know a systematic way to debug them?

:-( nope, not that verse in conda debugging unfortunately. Forgot even how to force a specific version build installation ;)

<details>
<summary>FWIW, for me an attempt to install git-annex now suggests to install git-annex-8.20200226 nodep_h1234567_1 build </summary> 

```shell
lena:~/anaconda-2018.12-3.7/bin
$> conda install -c conda-forge git-annex
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/yoh/anaconda-2018.12-3.7

  added / updated specs:
    - git-annex


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    git-annex-8.20200226       | nodep_h1234567_1        44.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        44.0 MB

The following packages will be UPDATED:

  git-annex                                    7.20190219-0 --> 8.20200226-nodep_h1234567_1


Proceed ([y]/n)? 

```
</details>

> The standalone build is only for Linux, no?

aren't OSX and Windows standalone because there is no other way? ;) FWIW, https://github.com/datalad/datalad/blob/master/tools/upgrade-annex-osx.sh is the script I used (awhile back) on OSX to "upgrade" git-annex.  Pretty much it just extracts content from .dmg and places into the target folder.

**Comment by yarikoptic** [comment]
sorry -- forgot that for Windows it indeed relies on git installation first, so may be not fully standalone there.

<details>
<summary>but on OSX seems to come bundled with git:</summary> 

```shell
datalads-imac:~ yoh$ ls /Applications/git-annex.app/Contents/MacOS/
README			git-annex		git-annex.MANIFEST	git-upload-pack		trustedkeys.gpg
bundle			git-annex-shell		git-receive-pack	man
git			git-annex-webapp	git-shell		runshell

```
</details>

**Comment by notestaff** [comment]
@yarikoptic @luispedro made this recipe's approach work on MacOS: https://github.com/bioconda/bioconda-recipes/pull/20723
maybe can back-port that here

**Pull request merged**
