### PR TITLE
switch to standalone git annex; update to version 7.20190219; rerender

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
oh, so you are giving up on building git-annex and just want to deploy the standalone builds provided by @joeyh?  isn't that somehow against conda-forge "philosophy"? ;)  
Sure thing then even OSX and Windows builds could be distributed "no problem" ;-)

**Comment by notestaff** [comment]
@yarikoptic it very much is 'against conda-forge "philosophy"'; I hope to eventually go back to building using stack.  But a working heresy beats non-working orthodoxy.  I've tried all I can think of, but conda-forge's Haskell support seems deeply broken.  I couldn't find a single recipe for something Haskell-based, in conda-forge or bioconda, that builds successfully with the current conda-forge.

The standalone build only works on Linux, so unfortunately this doesn't help with OSX or Windows recipes.

**Comment by notestaff** [comment]
@conda-forge/core @conda-forge/conda-build This recipe builds with many conda-build warnings, but tests pass.  Do the warnings matter?  Why are there warnings related to shared libraries, even though meta.yaml says '  binary_relocation: False'?

@eggzilla @conda-forge/ghc @conda-forge/ghc-bootstrap @conda-forge/stack @conda-forge/cabal Is there any working example of conda-forge recipe for a Haskell project built with stack, that works with the current version of conda-forge?

**Comment by yarikoptic** [comment]
one of my concerns for using standalone build is the http://git-annex.branchable.com/bugs/loadlocale_error_with_standalone_build/  but may be you provisioned for it in those patches you have?
But if heresy is to be committed, can't it be extended to OSX and Windows (just hypothetically speaking, not per se in the same PR)? ;)

**Comment by notestaff** [comment]
I filed two bug reports for the standalone build today, including one related to locales handling; it's not perfect, I just don't see an alternative.  Even if I manage to cobble together enough hacks and patches to make the stack build work, the result will be fragile/untrustworthy since I'm not a Haskell hacker.  The standalone build is put together by @joeyh, and is self-consistent by design.

"if heresy is to be committed" -- literally :)  If @joeyh puts together a standalone build for OSX then we can extend the conda recipe to OSX; but the current standalone build is explicitly for Linux.

**Comment by yarikoptic** [comment]
And what is "wrong" with https://downloads.kitenet.net/git-annex/OSX/current/10.10_Yosemite/git-annex.dmg besides having no version in url?

**Pull request merged**
